# create nework

networks:
  expense: {}

#create required voulmes

volumes:
  mysql:

services:

 #docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: mysql:1.0.0
    networks:
    - expense
    volumes:
    - mysql:/var/lib/mysql
    container_name: mysql

 # docker run -d --name backend --network expense  backend:1.0.0
  backend:
    image: backend:1.0.0
    networks:
    - expense
    container_name: backend
    deponds_on:
    - mysql
  
 #docker run -d --name fronted --network expense -p 80:80 frontend:1.0.0
  frontend:
    image: frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
